### PR TITLE
add option ‘initAfterDOMReady’ && fix error in $.addClass、$.removeClass

### PR DESCRIPTION
**Pull request by hannahORhannah**
1. fix: parameter ’i’ in $.addClass and $.removeClass
2. feat: add option ‘initAfterDOMReady’

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/vConsole?pullRequest=248) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/vConsole?pullRequest=248) before we can accept your contribution.<br/><hr/>**qiaoyi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/vConsole?pullRequest=248) it.</sub>

**Comment by Maizify** [comment]
请问 initAfterDOMReady 是出于什么情况考虑的呢？

**Comment by hannahORhannah** [comment]
原来的逻辑是只有load后初始化，但是我的场景是页面里有一些资源会加载超时，然后vConsole就会过很久才出来，使用上就会受影响。所以加initAfterDOMReady，然我可以在DOMContentLoaded之后就初始化vConsole

**Comment by Maizify** [comment]
我直接改成 DOMContentLoaded 吧，这个 PR 有些 conflict，就先不合了。

**Pull request closed without merging**
