### PR TITLE
fix: globalThis

### LINKED ISSUE #443: globalThis is not defined，v3.9.1在企业微信里还是不行哦
感谢反馈，可以试下v3.9.1。

_Originally posted by @Maizify in https://github.com/Tencent/vConsole/issues/438#issuecomment-887318208_

### PR DESCRIPTION
**Pull request by umarufans**
fix #443 

safely judge if `globalThis` exists.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/vConsole?pullRequest=445) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/vConsole?pullRequest=445) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/vConsole?pullRequest=445) it.</sub>

**Comment by XinChou16** [comment]
低版本浏览器只要不存在 `globalThis` 都会有这个问题，不止企业微信

**Comment by Maizify** [comment]
感谢提交。我已经直接把globalThis删掉了，先直接用window。因为其他模块也是一直在用window，等日后再统一加globalThis方法。

**Comment by fanerge** [comment]
请问下 npm 多少版本修复了这个bug？

**Pull request closed without merging**
